{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "8306218d_66f58cca",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5976
      },
      "writtenOn": "2021-09-08T00:28:14Z",
      "side": 1,
      "message": "TryBots beginning. Status page: https://farmer.golang.org/try?commit\u003dce13a359",
      "tag": "autogenerated:trybots~beginning",
      "revId": "ce13a3591eccc4e2859b39ba2249cef9be8531fe",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "81f7cfd9_e4d42225",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5976
      },
      "writtenOn": "2021-09-08T00:30:04Z",
      "side": 1,
      "message": "TryBots are happy.\n\n",
      "parentUuid": "8306218d_66f58cca",
      "tag": "autogenerated:trybots~happy",
      "revId": "ce13a3591eccc4e2859b39ba2249cef9be8531fe",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "fdbf2040_8028eaa6",
        "filename": "vulndb/internal/audit/utils.go",
        "patchSetId": 1
      },
      "lineNbr": 56,
      "author": {
        "id": 44473
      },
      "writtenOn": "2021-09-08T03:09:58Z",
      "side": 1,
      "message": "Curious how this is not resolving correctly.\n\nPackage\u0027s init() should be statically callable from the another package in their generated init(). It should not be callable from other locations. (You cannot directly call them or take their address IIRC.) Where is the issue manifesting in the init() functions or CHA saying func() var can be an init()?",
      "range": {
        "startLine": 56,
        "startChar": 2,
        "endLine": 56,
        "endChar": 124
      },
      "revId": "ce13a3591eccc4e2859b39ba2249cef9be8531fe",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}